---
fixtures:
  repositories:
    iptables: https://github.com/simp/pupmod-simp-iptables
    rsync: https://github.com/simp/pupmod-simp-rsync
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    xinetd: https://github.com/simp/pupmod-simp-xinetd
  symlinks:
    tftpboot: "#{source_dir}"
