---
fixtures:
  repositories:
    iptables: https://github.com/simp/pupmod-simp-iptables
    rsync: https://github.com/simp/pupmod-simp-rsync
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      branch: master
    xinetd: https://github.com/simp/pupmod-simp-xinetd
  symlinks:
    tftpboot: "#{source_dir}"
