---
HOSTS:
  el10:
    roles:
    - default
    platform: el-10-x86_64
    box: generic/centos10s
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      chef-current:
        baseurl: https://packages.chef.io/repos/yum/current/el/10/$basearch
        gpgkeys:
        - https://packages.chef.io/chef.asc
    family: centos-cloud/centos-stream-10
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  synced_folder: disabled
  type: aio
  vagrant_memsize: 256
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'openvox8') %>"
